### ISSUE TITLE
Add Counting Module

### ISSUE THREAD

**Issue by Zielmann** [Zielmann/FoxBot#20]
Module would allow users to create counters in the bot. Counters would need to be generated by the user each time the bot starts, so counter context would be restricted to only that stream. All active counters can be tracked in a basic dictionary.

Commands:

- [x] !newcount {count_name} {number}(opt) - Adds new counter to dictionary, starting at the specified number. If no number provided, starts at zero by default. Admin Only.

- [x] !count {count_name}(opt) - If count_name specified, will return that one count value. If not specified, lists out all active counters. All Users.

- [x] !add {count_name} {number}(opt) - Increments a count by the amount specified. If number is not included, defaults to increment by one. Admin only

- [x] !setcount {count_name} {number} - Sets count to the specified number. Admin only

- [x] !reset {count_name} - Sets the specified count back to zero. Admin only

- [x] !endcount {count_name} - deletes the specified count. Admin only

**Comment by cai-michael** [comment]
Is there a limit regarding the amount of counts listed in case they are ever saved?

**Comment by Zielmann** [comment]
Not sure how necessary a limit would be. The only practical issue I see with it would be if listing all active counts exceeds the 500ch message length limit. But that would probably be around 30-40 counts active at once, and that seems pretty unlikely.

Might be something to revisit though if saved counts is ever added.
